### ISSUE TITLE
'from' and 'to' keywords doesn't work

### ISSUE THREAD

**Issue by Aracki** [DONSA/alfred-google-translate#18]
From and to keywords doesn't work. Neither do symbols `<` & `>`.

I have set the default source and target. `gt <word>` works, but `gt fr>de <word>` doesn't.

**Comment by DONSA** [comment]
Thanks for the report. Is now fixed.
Please update the workflow.

**Comment by Aracki** [comment]
@DONSA It still doesn't work. What is the proper way to update the workflow?

**Comment by DONSA** [comment]
Download the [binary](https://github.com/DONSA/alfred-google-translate/blob/master/google-translate.alfredworkflow) double click and update.

**Comment by Aracki** [comment]
Now it's working. Thanks. 👍
